In [70]:
 # Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

In [71]:
weather_csv = '../WeatherPy/weather.csv'

weather_csv = pd.read_csv(weather_csv)

In [72]:
weather_df = pd.DataFrame(weather_csv).drop(['Unnamed: 0', 'Date'],axis=1)
weather_df = weather_df.dropna()
weather_df

,City,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Coutnry
0,yellowknife,62.46,-114.35,73.99,43,20,10.29,CA
1,busselton,-33.65,115.33,63.00,82,52,16.58,AU
2,hobart,-42.88,147.33,45.00,93,75,1.12,AU
3,tuy hoa,13.08,109.30,78.08,85,34,5.32,VN
4,ushuaia,-54.80,-68.30,33.80,95,40,16.11,AR
...,...,...,...,...,...,...,...,...
551,broken hill,-31.95,141.43,48.20,76,58,14.99,AU
552,newcastle,-32.93,151.78,55.40,100,90,23.04,AU
553,husavik,66.04,-17.34,46.40,75,20,9.17,IS
554,inuvik,68.35,-133.72,69.80,52,75,5.82,CA
555,wajir,1.75,40.06,77.86,57,0,18.10,KE

In [73]:
weather_df['Humidity'].max()

100

In [74]:
gmaps.configure(api_key=g_key)

# store parameters for heatmap in variable
locations = weather_df[["Latitude","Longitude"]]
humidity = weather_df['Humidity']

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=3)

# Add heat layer
fig.add_layer(heat_layer)

#display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [77]:
# create df to hold only cities with 'perfect weather'
perfect_df = weather_df.loc[(weather_df['Max Temperature'] >=70) & (weather_df['Max Temperature'] <=75)
                           & (weather_df['Wind Speed'] <=10)& (weather_df['Cloudiness'] <=30)& (weather_df['Humidity'] >=40)]
perfect_df

,City,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Coutnry
28,lata,40.16,-8.33,71.01,77,0,1.99,PT
81,zhoucheng,35.91,116.31,75.00,47,19,1.99,CN
134,caravelas,-17.71,-39.25,71.56,83,5,5.68,BR
168,vila franca do campo,37.72,-25.43,71.60,88,20,8.05,PT
189,durusu,41.31,28.68,73.40,94,0,5.82,TR
217,novozavedennoye,44.26,43.64,73.40,53,0,6.71,RU
290,niksar,40.59,36.95,70.59,58,0,4.83,TR
293,pafos,34.77,32.42,73.40,73,0,4.70,CY
387,poya,-21.35,165.15,71.15,78,2,7.70,NC
398,muros,42.78,-9.06,71.01,70,0,1.99,ES
414,agucadoura,41.43,-8.78,71.01,88,0,9.17,PT
415,baie-comeau,49.22,-68.15,71.60,68,1,8.05,CA
490,athabasca,54.72,-113.29,74.97,45,22,7.65,CA
531,bassano,50.78,-112.47,73.99,43,0,1.99,CA
544,weinan,34.50,109.51,75.00,94,0,4.47,CN

In [81]:
perfect_df['Hotel'] = ""
perfect_df

C:\Users\vmdin\anaconda3\envs\NewPythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,City,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Coutnry,Hotel
28,lata,40.16,-8.33,71.01,77,0,1.99,PT,
81,zhoucheng,35.91,116.31,75.00,47,19,1.99,CN,
134,caravelas,-17.71,-39.25,71.56,83,5,5.68,BR,
168,vila franca do campo,37.72,-25.43,71.60,88,20,8.05,PT,
189,durusu,41.31,28.68,73.40,94,0,5.82,TR,
217,novozavedennoye,44.26,43.64,73.40,53,0,6.71,RU,
290,niksar,40.59,36.95,70.59,58,0,4.83,TR,
293,pafos,34.77,32.42,73.40,73,0,4.70,CY,
387,poya,-21.35,165.15,71.15,78,2,7.70,NC,
398,muros,42.78,-9.06,71.01,70,0,1.99,ES,
414,agucadoura,41.43,-8.78,71.01,88,0,9.17,PT,
415,baie-comeau,49.22,-68.15,71.60,68,1,8.05,CA,
490,athabasca,54.72,-113.29,74.97,45,22,7.65,CA,
531,bassano,50.78,-112.47,73.99,43,0,1.99,CA,
544,weinan,34.50,109.51,75.00,94,0,4.47,CN,

In [86]:
# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# geocoordinates
target_radius = 5000
target_type = "lodging"

# set up a parameters dictionary
params = {
    "radius": target_radius,
    "type": target_type,
    "key": g_key
}
hotel_name = []
# run a request using our params dictionary
for x, y  in perfect_df.iterrows():
    coordinates = f'{y["Latitude"]},{y["Longitude"]}'
    params['location'] = coordinates
    try:
        response = requests.get(base_url, params=params).json()
        location_data = response['results']
        hotel = location_data[0]['name']
        perfect_df.loc[x, 'Hotel'] = location_data[0]['name']
    except:
        print('City not found')
        perfect_df.loc[x, 'Hotel'] = 'NaN'
        pass

C:\Users\vmdin\anaconda3\envs\NewPythonData\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

City not found

In [97]:
perfect_df = perfect_df.loc[perfect_df['Hotel'] !='NaN']

In [91]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Coutnry}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in perfect_df.iterrows()]
locations = perfect_df[["Latitude", "Longitude"]]

In [96]:
# Add marker layer on top of heat map
markers = gmaps.marker_layer(locations,info_box_content=hotel_info)
fig.add_layer(markers)
# Display figure
fig

Figure(layout=FigureLayout(height='420px'))